name: my_sehat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # Data Classes
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  path_provider: ^2.1.3
  uuid: ^4.4.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  geolocator: ^11.1.0

  # Networking
  dio: ^5.4.3
  http: ^1.2.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

  # Navigation
  go_router: ^14.0.0

  # UI
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  image_picker: ^1.0.7

  # Local Storage
  shared_preferences: ^2.2.2

  image_picker: any
  signature: any
  flame: any
  shared_preferences: any
  audioplayers: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/stickers/cats/
    - assets/stickers/dogs/
